FROM python:3.11-slim

WORKDIR /app

COPY ../../search /app

RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    pyyaml

EXPOSE 8000

CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000"]