FROM python:3.11-slim

WORKDIR /app

COPY ../../inventory /app

RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    pandas \
    numpy

EXPOSE 8001

CMD ["uvicorn", "api.inventory_api:app", "--host", "0.0.0.0", "--port", "8001"]