FROM python:3.11-slim

WORKDIR /app

COPY ../../agents /app

RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    pandas

EXPOSE 8002

CMD ["uvicorn", "api.agent_api:app", "--host", "0.0.0.0", "--port", "8002"]